apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emojivoto-app
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/JedenFalls/GitOpsLearn.git
    targetRevision: HEAD
    path: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: emojivoto
    
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    